language: cpp
compiler:
  - clang
  - gcc
cache: ccache

addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libxml2-dev
      - libpcap-dev
      - libsystemd-journal-dev
      - libsctp-dev
      - libssl-dev

env:
  - DTLS="ON"
  - DTLS="OFF"

script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSUPPORT_JOURNALD=ON -DSUPPORT_DTLS="$DTLS" . && make && make test
